---
version: 1
disable_existing_loggers: false

root_level: INFO

formatters:
  standard:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  json:
    format: '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "logger": "%(name)s", "message": "%(message)s"}'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/cybersage.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  sentry:
    class: sentry_sdk.integrations.logging.SentryHandler
    level: ERROR
    formatter: json

loggers:
  cybersage:
    level: INFO
    handlers: [console, file, sentry]
    propagate: false

  uvicorn:
    level: INFO
    handlers: [console]
    propagate: false
